### PR TITLE
Change unsims -> unisim in SigasiProjectCreator.py

### PR DESCRIPTION
**Pull request by LukasVik**
Library is called unisim, although containing folder is named unisims in newer Vivado vesions

### CODE REVIEW

**Comment by LukasVik** [comment]
See for example Table 2-3 in UG900

**Comment by heeckhau** [comment]
I think the library name was always "unisim". I'll check

**Comment by heeckhau** [comment]
It is in our own documentation http://insights.sigasi.com/manual/libraries.html :smile: 

Thanks

**Comment by LukasVik** [comment]
Great. Thank you!

**Pull request merged**
